
shovel:
    host: 0.0.0.0
    port: 9000
    debug: True
    logLevel: INFO
rackhd:
    host: http://localhost
    port: 8080
    api: api/2.0
    debug: False
    verify_ssl: False
    amqp: 
        host: localhost
        port: 5672
ironic:
    os_username: admin
    os_password: password
    os_auth_url: http://10.240.19.168:5000/v2.0
    os_tenant_name: admin
    insecure : False

glance:
    os_username: admin
    os_password: password
    os_auth_url: http://10.240.19.168:5000/v2.0
    glance_url: http://10.240.19.168:9292
    os_tenant_name: admin
    insecure : False
